### ISSUE TITLE
add .gitignore file

### ISSUE THREAD

**Issue by tera3xbyte** [wahpratama/Jero-cashier#1]
## yang terhormat, bpk wahpratama.

saya selaku follower bapak. saya ingin memberikan saran kepada bapak untuk menambahkan file `.gitignore` pada repositori bapak, supaya repositori bapak tidak penuh.

_regards
~ tera3xbyte_

**Comment by wahpratama** [comment]
saya udah buat dari kemarin ada di client dan lupa pindah saya udah pindah dan belum pus sekian terimakasih

**Comment by tera3xbyte** [comment]
ok, issue solved
